apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: domain-bot-collection-cleaner
spec:
  schedule: "0 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: domain-bot-collection-cleaner
            image: 
            imagePullPolicy: Always
            env:
            - name: DISCOVERY_ENVIRONMENT_ID
              value:
            - name: DISCOVERY_COLLECTION_ID
              value: 
            - name: DISCOVERY_PASSWORD
              value: 
            - name: DISCOVERY_USERNAME
              value: 
            args:
          restartPolicy: OnFailure